#!/usr/bin/env bash
set -Eeuo pipefail
SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=../lib/common.sh
source "$SCRIPT_DIR/../lib/common.sh"
generate() {
  load_node_data; install -d -m 0755 "$WEB_ROOT"
  cat >"$WEB_ROOT/config.yaml" <<EOF
# Generated by Proxy Manager; this file contains no server private key.
mixed-port: 7890
allow-lan: false
mode: rule
log-level: warning
ipv6: false
unified-delay: true
tcp-concurrent: true
dns:
  enable: true
  listen: 127.0.0.1:1053
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  nameserver: [https://1.1.1.1/dns-query, https://dns.google/dns-query]
proxies:
  - name: "$NODE_NAME"
    type: vless
    server: "$SERVER"
    port: $PORT
    uuid: "$UUID"
    encryption: "none"
    network: tcp
    udp: true
    tls: true
    flow: xtls-rprx-vision
    servername: "$SNI"
    client-fingerprint: chrome
    reality-opts: {public-key: "$PUBLIC_KEY", short-id: "$SHORT_ID"}
proxy-groups:
  - {name: Proxy, type: select, proxies: ["$NODE_NAME", DIRECT]}
rules: [MATCH,Proxy]
EOF
  chmod 0644 "$WEB_ROOT/config.yaml"; say "URL: ${SUBSCRIPTION_URL:-http://$SERVER/clash/config.yaml}"
}
case "${1:-}" in generate) require_root; generate; exit;; show) load_node_data; say "$SUBSCRIPTION_URL"; exit;; "") ;; *) die "Usage: subscription.sh [generate|show]";; esac
require_root
while true; do clear; say "===== Clash 订阅 ====="; say "1. 生成配置"; say "2. 显示订阅地址"; say "0. 返回"; read -r -p "请选择: " c; case "$c" in 1) generate; read -r -p "请按回车继续..." _;;2) load_node_data; say "$SUBSCRIPTION_URL"; read -r -p "请按回车继续..." _;;0) exit;;*) say "无效选择。";;esac; done
