#!/usr/bin/env bash
set -Eeuo pipefail
SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=../lib/common.sh
source "$SCRIPT_DIR/../lib/common.sh"

# 输出一个 VLESS-Reality 节点条目。参数：名称 端口 UUID 公钥 shortId 是否加分片(1/0)
# 分片（fragment）用于 WiFi web 跳验证：拆分 TLS ClientHello 以抗浅层 SNI/DPI。
proxy_yaml() {
  local name="$1" port="$2" uuid="$3" pub="$4" sid="$5" frag="$6" frag_yaml=""
  if [[ "$frag" == "1" ]]; then
    frag_yaml='
    fragment:
      packets: tlshello
      length: 100-200
      interval: 20-40'
  fi
  printf '  - name: "%s"\n    type: vless\n    server: "%s"\n    port: %s\n    uuid: "%s"\n    encryption: "none"\n    network: tcp\n    udp: true\n    tls: true\n    flow: xtls-rprx-vision\n    servername: "%s"\n    client-fingerprint: chrome\n    reality-opts:\n      public-key: "%s"\n      short-id: "%s"%s\n' \
    "$name" "$SERVER" "$port" "$uuid" "$SNI" "$pub" "$sid" "$frag_yaml"
}

generate() {
  load_node_data; install -d -m 0755 "$WEB_ROOT"
  local main_ok=0 wifi_ok=0
  if [[ -n "${UUID:-}" && -n "${PUBLIC_KEY:-}" && -n "${SHORT_ID:-}" && -n "${PORT:-}" ]]; then main_ok=1; fi
  if [[ "${WIFI:-0}" == "1" && -n "${WIFI_UUID:-}" && -n "${WIFI_PUBLIC_KEY:-}" && -n "${WIFI_SHORT_ID:-}" && -n "${WIFI_PORT:-}" ]]; then wifi_ok=1; fi
  (( main_ok || wifi_ok )) || die "没有可用节点：主节点与 WiFi 跳验证节点均缺失。"
  # 订阅随机令牌：订阅路径不可猜测。固定路径 /clash/config.yaml 会被扫段者直接取走
  # 含 UUID 的节点配置（UUID 即 VLESS 唯一凭证）。
  if [[ -z "${SUB_TOKEN:-}" ]]; then
    require_command openssl
    SUB_TOKEN="$(openssl rand -hex 16)"
    env_upsert "$NODE_FILE" SUB_TOKEN "$SUB_TOKEN"
  fi
  SUBSCRIPTION_URL="http://$SERVER/clash/$SUB_TOKEN/config.yaml"
  env_upsert "$NODE_FILE" SUBSCRIPTION_URL "$SUBSCRIPTION_URL"
  chmod 0600 "$NODE_FILE"
  local sub_dir="$WEB_ROOT/$SUB_TOKEN"
  install -d -m 0755 "$sub_dir"
  {
    printf '# Generated by Proxy Manager; this file contains no server private key.\n'
    printf 'mixed-port: 7890\nallow-lan: false\nmode: rule\nlog-level: warning\nipv6: false\nunified-delay: true\ntcp-concurrent: true\npacket-encoding: xudp\n'
    printf 'dns:\n  enable: true\n  ipv6: false\n  enhanced-mode: fake-ip\n  fake-ip-range: 198.18.0.1/16\n  listen: 127.0.0.1:1053\n'
    printf '  nameserver:\n    - https://1.1.1.1/dns-query\n    - https://8.8.8.8/dns-query\n'
    printf '  fallback:\n    - https://dns.google/dns-query\n    - https://1.0.0.1/dns-query\n'
    printf '  proxy-server-nameserver:\n    - https://1.1.1.1/dns-query\n'
    printf 'proxies:\n'
    if (( main_ok )); then
      proxy_yaml "${NODE_NAME:-Reality-$SERVER}" "$PORT" "$UUID" "$PUBLIC_KEY" "$SHORT_ID" "${BYPASS:-0}"
    fi
    if (( wifi_ok )); then
      proxy_yaml "${WIFI_NODE_NAME:-WiFi-$SERVER}" "$WIFI_PORT" "$WIFI_UUID" "$WIFI_PUBLIC_KEY" "$WIFI_SHORT_ID" 1
    fi
    printf 'proxy-groups:\n  - name: Proxy\n    type: select\n    proxies:\n'
    if (( main_ok )); then printf '      - "%s"\n' "${NODE_NAME:-Reality-$SERVER}"; fi
    if (( wifi_ok )); then printf '      - "%s"\n' "${WIFI_NODE_NAME:-WiFi-$SERVER}"; fi
    printf '      - DIRECT\n'
    printf 'rules:\n  - MATCH,Proxy\n'
  } >"$sub_dir/config.yaml"
  chmod 0644 "$sub_dir/config.yaml"
  # 迁移：删除旧版固定路径订阅文件，令可猜测地址彻底失效
  rm -f "$WEB_ROOT/config.yaml"
  # 自检：历史问题为 nginx 未启动导致订阅空/不可用
  [[ -s "$sub_dir/config.yaml" ]] || die "Clash 配置生成失败（文件为空）。"
  if ! systemctl is-active --quiet nginx 2>/dev/null; then
    say "⚠ 自检: nginx 未运行，订阅 URL 暂时无法访问 —— 请运行主菜单 5 启动 Web 订阅服务。"
  elif command -v curl >/dev/null 2>&1; then
    code=$(curl -o /dev/null -s -w '%{http_code}' "http://127.0.0.1/clash/$SUB_TOKEN/config.yaml" || true)
    if [[ "$code" == "200" ]]; then say "✓ 自检: 订阅 URL 本地可访问 (HTTP 200)。"; else say "⚠ 自检: 本地请求返回 HTTP ${code:-无响应}（若仅本机测不到公网 IP 属正常，请以浏览器访问为准）。"; fi
  fi
  say "URL: $SUBSCRIPTION_URL"
  (( wifi_ok )) && say "✓ 订阅含 WiFi web 跳验证专属节点（端口 ${WIFI_PORT}，带 fragment 分片）。"
  say "⚠ 订阅地址含随机令牌，等同节点凭证，请勿泄露。"
}
case "${1:-}" in generate) require_root; generate; exit;; show) load_node_data; say "${SUBSCRIPTION_URL:-订阅尚未生成，请先执行生成。}"; exit;; "") ;; *) die "Usage: subscription.sh [generate|show]";; esac
require_root
while true; do clear; say "===== Clash 订阅 ====="; say "1. 生成配置"; say "2. 显示订阅地址"; say "0. 返回"; read -r -p "请选择: " c; case "$c" in 1) generate; read -r -p "请按回车继续..." _;;2) load_node_data; say "${SUBSCRIPTION_URL:-订阅尚未生成，请先执行生成。}"; read -r -p "请按回车继续..." _;;0) exit;;*) say "无效选择。";;esac; done
