#!/usr/bin/env bash
set -Eeuo pipefail
SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
source "$SCRIPT_DIR/../lib/common.sh"

# 独立 nginx 站点：不再依赖发行版默认站点的 root 恰好是 /var/www/html
NGINX_CONF="/etc/nginx/sites-available/proxy-manager.conf"
NGINX_LINK="/etc/nginx/sites-enabled/proxy-manager.conf"

write_nginx_conf() {
  # 仅当内核启用 IPv6 时写入 [::]:80，避免无 IPv6 的机器上 nginx 启动失败
  local v6=""
  [[ -f /proc/net/if_inet6 ]] && v6="listen [::]:80 default_server;"
  cat >"$NGINX_CONF" <<EOF
# Generated by Proxy Manager — subscription serving (:80 default_server)
server {
    listen 80 default_server;
    ${v6}
    server_name _;
    root /var/www/html;
    index index.html index.nginx-debian.html;

    # 订阅文件位于 /var/www/html/clash/<随机令牌>/config.yaml（路径不可猜测）
    location /clash/ {
        autoindex off;
        add_header Cache-Control "no-store";
    }
}
EOF
}

# 启用本站点并停用发行版默认站点（避免 default_server 冲突）；校验失败自动回滚
configure_nginx() {
  local had_default=0
  [[ -e /etc/nginx/sites-enabled/default || -L /etc/nginx/sites-enabled/default ]] && had_default=1
  write_nginx_conf
  ln -sfn "$NGINX_CONF" "$NGINX_LINK"
  if [[ "$had_default" == 1 ]]; then rm -f /etc/nginx/sites-enabled/default; fi
  if nginx -t >/dev/null 2>&1; then
    systemctl reload nginx 2>/dev/null || systemctl restart nginx
    say "nginx 订阅站点已启用（proxy-manager.conf 接管 :80 default_server）。"
  else
    say "⚠ nginx 配置校验失败，输出如下："
    nginx -t 2>&1 || true
    rm -f "$NGINX_LINK"
    if [[ "$had_default" == 1 ]]; then ln -sfn /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default; fi
    nginx -t >/dev/null 2>&1 && systemctl reload nginx 2>/dev/null || true
    die "nginx 配置失败，已回滚到原状态。请检查上方 nginx -t 输出。"
  fi
}

install_web() {
  require_command nginx
  install -d -m 0755 "$WEB_ROOT"
  systemctl enable --now nginx
  configure_nginx
  # 幂等重新生成：同时确保随机令牌与最新订阅路径存在
  "$SCRIPT_DIR/subscription.sh" generate
  command -v ufw >/dev/null && ufw status | grep -q 'Status: active' && ufw allow 80/tcp || true
  load_node_data
  say "已发布：${SUBSCRIPTION_URL:-订阅地址见上方输出}"
}
require_root
while true; do clear; say "===== Web 订阅服务 ====="; say "1. 启用 Nginx 并发布配置"; say "2. 查看状态"; say "0. 返回"; read -r -p "请选择: " c; case "$c" in 1) install_web; read -r -p "请按回车继续..." _;;2) systemctl --no-pager status nginx || true; read -r -p "请按回车继续..." _;;0) exit;;*) say "无效选择。";;esac; done
